#!/bin/sh

#   WARNING   this file is automatically generated by RT-Druid

#   If you want modify this file, you should move it to a safe folder,
#   like the project's root, and update the path inside the project 
#   properties "C/C++ Make Project" -> "Build command"
#   i.e.   ${workspace_loc:di_amp}/make_launcher.bat


ERIKA_FILES=/home/student/.eclipse/org.eclipse.platform_3.5.0_155965261/plugins/com.eu.evidence.ee_1.6.0.20111019_2125/ee_files
export ERIKA_FILES

make $@
